
exports.UPDATE_EVENT_BREAKPOINTS = 'UPDATE_EVENT_BREAKPOINTS';

exports.TOGGLE_PRETTY_PRINT = 'TOGGLE_PRETTY_PRINT';
exports.BLACKBOX = 'BLACKBOX';
exports.SELECT_SOURCE = 'SELECT_SOURCE';

exports.INC_NUMBER = 'INC_NUMBER';
